name: MoSE
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - anyio
  - argon2-cffi
  - async_generator
  - attrs=21.4.0
  - babel=2.9.1
  - backcall
  - blas
  - bleach
  - bottleneck
  - brotli
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - cryptography
  - cudatoolkit
  - cycler
  - dbus
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - ffmpeg
  - fontconfig
  - fonttools
  - freetype
  - gflags
  - giflib
  - glib
  - gmp
  - gnutls
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - importlib_metadata
  - iniconfig
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - jpeg
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - kiwisolver
  - lame
  - lcms2
  - ld_impl_linux-64
  - libblas
  - libfaiss
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran4
  - libgomp
  - libiconv
  - libidn2
  - liblapack
  - libpng
  - libprotobuf
  - libsodium
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libunistring
  - libuuid
  - libuv
  - libwebp
  - libwebp-base
  - libxcb
  - libxml2
  - lz4-c
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - nettle
  - notebook
  - numexpr
  - olefile
  - openh264
  - openssl
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pip
  - pluggy
  - prometheus_client
  - prompt-toolkit
  - ptyprocess
  - py
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - pytest
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pytorch-mutex
  - pytz
  - pyzmq
  - qt
  - readline
  - requests
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - sip
  - six
  - sniffio
  - sqlite
  - terminado
  - testpath
  - tk
  - toml
  - torchaudio
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - tsnecuda
  - typing_extensions
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - absl-py
    - beautifulsoup4
    - cachetools
    - cython
    - easydict
    - google
    - google-auth
    - google-auth-oauthlib
    - grpcio
    - h5py
    - imageio
    - importlib-metadata
    - joblib
    - markdown
    - markupsafe
    - networkx
    - numpy
    - opencv-python
    - pillow
    - pot
    - protobuf
    - psutil
    - pyasn1
    - pyasn1-modules
    - pywavelets
    - pyyaml
    - requests-oauthlib
    - rsa
    - scikit-image
    - scikit-learn
    - soupsieve
    - tensorboard
    - tensorboard-data-server
    - tensorboard-plugin-wit
#    - tensorboardx==2.5.1
#    - threadpoolctl==3.1.0
#    - tifffile==2022.10.10
#    - torchstat==0.0.7
#    - werkzeug==2.2.2
#prefix: /public/home/gaozht/.conda/envs/Poly2
